// Code generated by go-swagger; DO NOT EDIT.

// Package v1 Expenses
//
//  Documentation of the expenses API.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package v1
