// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetExpenseByIDParams creates a new GetExpenseByIDParams object
// no default values defined in spec.
func NewGetExpenseByIDParams() GetExpenseByIDParams {

	return GetExpenseByIDParams{}
}

// GetExpenseByIDParams contains all the bound params for the get expense by ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters Get expense by ID
type GetExpenseByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the expense
	  Required: true
	  In: path
	*/
	ExpenseID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetExpenseByIDParams() beforehand.
func (o *GetExpenseByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rExpenseID, rhkExpenseID, _ := route.Params.GetOK("expenseId")
	if err := o.bindExpenseID(rExpenseID, rhkExpenseID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExpenseID binds and validates parameter ExpenseID from path.
func (o *GetExpenseByIDParams) bindExpenseID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ExpenseID = raw

	return nil
}
