// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetExpensesParams creates a new GetExpensesParams object
// no default values defined in spec.
func NewGetExpensesParams() GetExpensesParams {

	return GetExpensesParams{}
}

// GetExpensesParams contains all the bound params for the get expenses operation
// typically these are obtained from a http.Request
//
// swagger:parameters Get expenses
type GetExpensesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The earliest date to fetch expenses from
	  In: query
	*/
	DateFrom *string
	/*The latest date to fetch expenses from
	  In: query
	*/
	DateTo *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetExpensesParams() beforehand.
func (o *GetExpensesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDateFrom, qhkDateFrom, _ := qs.GetOK("dateFrom")
	if err := o.bindDateFrom(qDateFrom, qhkDateFrom, route.Formats); err != nil {
		res = append(res, err)
	}

	qDateTo, qhkDateTo, _ := qs.GetOK("dateTo")
	if err := o.bindDateTo(qDateTo, qhkDateTo, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDateFrom binds and validates parameter DateFrom from query.
func (o *GetExpensesParams) bindDateFrom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DateFrom = &raw

	return nil
}

// bindDateTo binds and validates parameter DateTo from query.
func (o *GetExpensesParams) bindDateTo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DateTo = &raw

	return nil
}
