// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetExpenseByIDHandlerFunc turns a function with the right signature into a get expense by ID handler
type GetExpenseByIDHandlerFunc func(GetExpenseByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetExpenseByIDHandlerFunc) Handle(params GetExpenseByIDParams) middleware.Responder {
	return fn(params)
}

// GetExpenseByIDHandler interface for that can handle valid get expense by ID params
type GetExpenseByIDHandler interface {
	Handle(GetExpenseByIDParams) middleware.Responder
}

// NewGetExpenseByID creates a new http.Handler for the get expense by ID operation
func NewGetExpenseByID(ctx *middleware.Context, handler GetExpenseByIDHandler) *GetExpenseByID {
	return &GetExpenseByID{Context: ctx, Handler: handler}
}

/*GetExpenseByID swagger:route GET /expenses/{expenseId} getExpenseById

Get expense by ID

*/
type GetExpenseByID struct {
	Context *middleware.Context
	Handler GetExpenseByIDHandler
}

func (o *GetExpenseByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetExpenseByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
