// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Expenses expenses
//
// swagger:model Expenses
type Expenses struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// expenses
	// Required: true
	Expenses []*Expense `json:"expenses"`
}

// Validate validates this expenses
func (m *Expenses) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpenses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Expenses) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}

func (m *Expenses) validateExpenses(formats strfmt.Registry) error {

	if err := validate.Required("expenses", "body", m.Expenses); err != nil {
		return err
	}

	for i := 0; i < len(m.Expenses); i++ {
		if swag.IsZero(m.Expenses[i]) { // not required
			continue
		}

		if m.Expenses[i] != nil {
			if err := m.Expenses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("expenses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Expenses) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Expenses) UnmarshalBinary(b []byte) error {
	var res Expenses
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
